### ISSUE TITLE
why crfs on widget form?

### ISSUE THREAD

**Issue by alisherdavronov** [pistol88/yii2-paymaster#1]
https://github.com/pistol88/yii2-paymaster/blob/master/widgets/views/paymentForm.php#L6

**Comment by pistol88** [comment]
Робот Паймастера будет встречен 400 ошибкой иначе. Думаешь, следует enableCsrfValidation=>false поставить в эктионе?

**Comment by alisherdavronov** [comment]
Да, думаю лучше отключить enableCsrfValidation в экшне, все равно там есть проверка по хешу.

**Comment by pistol88** [comment]
Посмотрел - enableCsrfValidation уже есть в эктионе для робота Паймастера. А этот csrf я вставил, чтобы юзер вернулся без проблем на страницу "спасибо за заказ" (туда он отправится с непустым _POST).
